#!/usr/bin/env python3
"""Register a Colony agent wallet with Worldcoin AgentKit and store the receipt."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from colony_harness.env import load_env_file
from colony_harness.world import (
    DEFAULT_WORLD_VERIFICATION_STORE,
    WorldVerificationStore,
    build_verification,
)


def main() -> None:
    args = parse_args()
    load_env_file(args.env)
    identity = _load_identity(args.identity_json)
    records = _find_identity_records(identity, args.agents)
    store = WorldVerificationStore(_resolve_world_verifications(args))
    total = len(records)
    for index, record in enumerate(records, start=1):
        _register_one(record, args=args, store=store, index=index, total=total)


def _register_one(
    record: dict[str, Any],
    *,
    args: argparse.Namespace,
    store: WorldVerificationStore,
    index: int,
    total: int,
) -> None:
    agent_id = str(record["agent_id"])
    wallet_address = str(record["addr"])
    ens_name = str(record["ens_name"])
    existing = store.by_wallet(wallet_address)
    if existing is not None and args.skip_existing:
        print(f"\n[{index}/{total}] Skipping {agent_id}: receipt already stored.")
        return

    print(f"\n[{index}/{total}] Worldcoin AgentKit registration")
    print(f"Agent:  {agent_id}")
    print(f"ENS:    {ens_name}")
    print(f"Wallet: {wallet_address}")

    if args.record_existing:
        receipt = {
            "tx_hash": args.tx_hash or "",
            "merkle_root": args.merkle_root or "",
            "nullifier_hash": args.nullifier_hash or "",
        }
    else:
        receipt = _run_agentkit_register(wallet_address, package=args.package, show_qr=not args.no_qr)

    verification = build_verification(
        agent_id=agent_id,
        wallet_address=wallet_address,
        ens_name=ens_name,
        tx_hash=receipt.get("tx_hash", ""),
        merkle_root=receipt.get("merkle_root", ""),
        nullifier_hash=receipt.get("nullifier_hash", ""),
    )
    store.add(verification)
    print(f"Stored World AgentKit receipt: {store.path}")
    print(f"Tx: {verification.tx_hash or '(not recorded)'}")
    print(f"Nullifier: {verification.nullifier_hash or '(not recorded)'}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "agents",
        nargs="+",
        help="Agent ids or wallet addresses to register, e.g. ant_0000 ant_0007 ant_0012.",
    )
    parser.add_argument("--env", default="colony/.env", help="Optional .env path.")
    parser.add_argument(
        "--identity-json",
        default="colony/data/ens-identities.demo.json",
        help="Identity JSON generated by run_demo.py/run_match.py --identity-out.",
    )
    parser.add_argument(
        "--world-verifications",
        default=None,
        help="Gitignored local Worldcoin AgentKit receipt store. Defaults to COLONY_WORLD_VERIFICATIONS.",
    )
    parser.add_argument(
        "--package",
        default="@worldcoin/agentkit-cli",
        help="NPM package used by npx for Worldcoin AgentKit registration.",
    )
    parser.add_argument(
        "--record-existing",
        action="store_true",
        help="Do not run the CLI; record an already completed AgentKit registration.",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip agents that already have a receipt in the local store.",
    )
    parser.add_argument(
        "--no-qr",
        action="store_true",
        help="Do not render a terminal QR code when the World App verification URL appears.",
    )
    parser.add_argument("--tx-hash", default="")
    parser.add_argument("--merkle-root", default="")
    parser.add_argument("--nullifier-hash", default="")
    return parser.parse_args()


def _resolve_world_verifications(args: argparse.Namespace) -> str:
    return args.world_verifications or os.environ.get("COLONY_WORLD_VERIFICATIONS") or str(DEFAULT_WORLD_VERIFICATION_STORE)


def _load_identity(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    if not source.exists():
        raise SystemExit(f"Identity JSON not found: {source}")
    return json.loads(source.read_text(encoding="utf-8"))


def _find_identity_record(identity: dict[str, Any], wanted: str) -> dict[str, Any]:
    normalized = wanted.lower()
    for record in identity.get("records") or []:
        wallet = str(record.get("addr") or "").lower()
        agent_id = str(record.get("agent_id") or "").lower()
        if normalized in {wallet, agent_id}:
            if not record.get("addr"):
                raise SystemExit(f"{record.get('agent_id')} has no wallet address.")
            return dict(record)
    raise SystemExit(f"No identity record matched {wanted}.")


def _find_identity_records(identity: dict[str, Any], wanted_agents: list[str]) -> list[dict[str, Any]]:
    records_by_agent = {str(record.get("agent_id") or "").lower(): dict(record) for record in identity.get("records") or []}
    records_by_wallet = {str(record.get("addr") or "").lower(): dict(record) for record in identity.get("records") or []}
    matched: list[dict[str, Any]] = []
    missing: list[str] = []
    for wanted in wanted_agents:
        normalized = wanted.lower()
        record = records_by_agent.get(normalized) or records_by_wallet.get(normalized)
        if record is None:
            missing.append(wanted)
            continue
        if not record.get("addr"):
            raise SystemExit(f"{record.get('agent_id')} has no wallet address.")
        matched.append(record)
    if missing:
        available = sorted(records_by_agent)
        sample = ", ".join(available[:8])
        suffix = "..." if len(available) > 8 else ""
        raise SystemExit(
            "Identity JSON is missing requested agents: "
            f"{', '.join(missing)}. "
            f"It currently contains {len(available)} agents: {sample}{suffix}. "
            "Regenerate it with enough agents before registering World IDs."
        )
    return matched


def _run_agentkit_register(wallet_address: str, *, package: str, show_qr: bool) -> dict[str, str]:
    cmd = ["npx", "-y", package, "register", wallet_address]
    print("\nStarting Worldcoin AgentKit registration.")
    print("Scan the QR code/link shown by the CLI when prompted.\n")
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    lines: list[str] = []
    shown_urls: set[str] = set()
    assert process.stdout is not None
    for line in process.stdout:
        lines.append(line)
        print(line, end="")
        if show_qr:
            for url in _world_verify_urls(line):
                if url in shown_urls:
                    continue
                shown_urls.add(url)
                _print_world_qr(url)
    code = process.wait()
    output = "".join(lines)
    if "ALREADY_REGISTERED" in output:
        receipt = _parse_agentkit_output(output)
        if not receipt.get("nullifier_hash"):
            receipt["nullifier_hash"] = _match(r'(?:\\?"humanId\\?")\s*:\s*(?:\\?")(0x[a-fA-F0-9]+)(?:\\?")', output)
        print("Worldcoin AgentKit says this address is already registered; storing the local receipt and continuing.")
        return receipt
    if code != 0:
        raise SystemExit(f"Worldcoin AgentKit CLI failed with exit code {code}")
    receipt = _parse_agentkit_output(output)
    if "Agent registered on World Chain" not in output and not _has_receipt(receipt):
        raise SystemExit("Worldcoin AgentKit CLI completed but did not report a World Chain registration.")
    return receipt


def _parse_agentkit_output(output: str) -> dict[str, str]:
    return {
        "tx_hash": _match(r"(?:\bTx\s+|\btxHash:\s*)(0x[a-fA-F0-9]{64})", output),
        "merkle_root": _match(r"(?:Merkle root:|\broot:)\s+(0x[a-fA-F0-9]+)", output),
        "nullifier_hash": _match(r"(?:Nullifier hash:|\bnullifierHash:)\s+(0x[a-fA-F0-9]+)", output),
    }


def _has_receipt(receipt: dict[str, str]) -> bool:
    return bool(receipt.get("tx_hash") or receipt.get("nullifier_hash"))


def _world_verify_urls(line: str) -> list[str]:
    return [match.group(1).rstrip(".,)") for match in re.finditer(r"(https://world\.org/verify\?\S+)", line)]


def _print_world_qr(url: str) -> None:
    print("\nWorld App QR:")
    try:
        import qrcode
    except ImportError:
        print(f"QR renderer unavailable; open this on your phone: {url}\n")
        return
    qr = qrcode.QRCode(border=1)
    qr.add_data(url)
    qr.make(fit=True)
    qr.print_ascii(out=sys.stdout, tty=False, invert=True)
    print(f"\nOpen on phone: {url}\n")


def _match(pattern: str, output: str) -> str:
    match = re.search(pattern, output)
    return match.group(1) if match else ""


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted", file=sys.stderr)
        raise SystemExit(130)
